# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ingenium Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/leoboyerbx/ingenium-launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/leoboyerbx/ingenium-launcher"
supportLink = "https://github.com/leoboyerbx/ingenium-launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Ingenium"
welcomeDescription = "Ce launcher permet de se connecter à notre serveur Minecraft vanilla+Create. Pour le moment il est pas brandé et est en anglais mais il fonctionne !"
welcomeDescCTA = "Alors, on attend quoi ?"
