[ejs.landing]
updateAvailableTooltip = "Update Available"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Réglages"
serverStatus = "SERVER"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "ACTU"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Chargement des actualités.."
newsErrorFailedSpan = "Impossible de charger les actualités."
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur non valide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Obligatoire"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Mot de passe oublié ?"
loginRememberMeText = "Se souvenir de moi"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants"
launchFullscreenTitle = "Lancer en plein écran"
autoConnectTitle = "Se connecter automatiquement au serveur au lancement"
launchDetachedTitle = "Lancer le jeu dans un processus détaché du lanceur"
launcherTabHeaderDesc = "Options liées au launcher lui-même"
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "A propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options de lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchDetachedDesc = "Si le jeu n'est pas détaché, la fermeture du launcher entraînera également la fermeture du jeu."
tabModsHeaderText = "Paramètres de mods"
tabModsHeaderDesc = "Activer ou désactiver des mods."
switchServerButton = "Changer"
requiredMods = "Mods obligatoires"
optionalMods = "Mods optionnels"
dropinMods = "Mods personnalisés"
addMods = "Ajouter des Mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = " Packs de shaders "
shaderpackDesc = "Activer ou désactiver les shaders. Veuillez noter que les shaders ne fonctionneront correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un pack de shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = " Mémoire vive maximale "
minRAM = "Mémoire vive minimale"
memoryDesc = "La mémoire vive minimale recommandée est de 3Go. Régler les valeurs minimale et maximale sur la même valeur peut réduire le lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin doit se finir par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options additionnelles pour la JVM"
jvmOptsDesc = "Options de runtime à passer à la JVM. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être incluses."
launcherTabHeaderText = "Réglages du launcher"
allowPrereleaseTitle = "Autoriser les pré-versions."
allowPrereleaseDesc = "Les pré-versions comprennent de nouvelles fonctionnalités qui peuvent ne pas avoir été entièrement testées ou intégrées. <br>Ce sera toujours le cas si vous utilisez une pré-version."
dataDirectoryTitle = "Répertoire des données"
selectDataDirectory = "Sélectionner le répertoire des données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales seront stockés dans le répertoire de données.<br>Les captures d'écran et les sauvegardes du monde sont stockées dans le dossier d'instance de la configuration de serveur correspondante."
aboutTabHeaderText = " À propos"
aboutTabHeaderDesc = "Informations et notes de mise à jour de la version actuelle"
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de publication"
changelog = "Journal des modifications"
noReleaseNotes = "Pas de notes de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et vérifier les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Recharger les notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "Attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion à Microsoft"
microsoftLogoutTitle = "Déconnexion de Microsoft"

[js.login]
login = " CONNEXION "
loggingIn = " CONNEXION "
success = "RÉUSSITE"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur non valide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
okay = "Ok"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = " Aucun serveur sélectionné "
loading = " Chargement... "

[js.landing.serverStatus]
server = " SERVEUR "
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des informations système..."
noCompatibleJava = "Aucune installation compatible<br>Java trouvée"
installJavaMessage = "Afin de lancer Minecraft, vous avez besoin d'une installation 64 bits de Java {major}. Voulez-vous en installer une copie ?"
installJava = "Installer Java"
installJavaManually = "Installation manuelle"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur pendant le téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de détails"
javaRequired = "Java est requis<br>pour lancer le jeu"
javaRequiredMessage = 'Une installation valide de Java {major} est nécessaire au lancement.'
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la recherche de la distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a un mauvais hachage, le fichier peut être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations sur le serveur..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité du fichier.."
errorDuringFileVerificationTitle = "Erreur lors de la vérification du fichier"
downloadingFiles = "Téléchargement de fichiers.."
errorDuringFileDownloadTitle = "Erreur pendant le téléchargement du fichier"
preparingToLaunch = "Préparation du lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Terminé. Profitez du serveur !"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Chargement des actualités"

[js.landing.discord]
loading = " Chargement du jeu... "
joining = "C'est parti pour Ingenium !"
joined = "Explore le monde !"

[js.overlay]
dismiss = "Masquer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose n'a pas fonctionné"
errorMessage = "L'authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose n'a pas fonctionné"
errorMessage = "La déconnexion Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Avertissement<br>Ceci est votre unique compte"
lastAccountWarningMessage = "Pour utiliser le launcher, vous devez être connecté à au moins un compte. Vous devrez vous connecter à nouveau.<br><br>Confirmez-vous la déconnexion ?"
confirmButton = "Je confirme"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>Mod personnalisé {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas en cours d'utilisation et réessayez."
failedToggleTitle = " Échec du basculement<br>d'un ou plusieurs Mods  personnalisés"
okButton = "Ok"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({fournisseur})"
invalidSelection = "Sélection non valide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Préversion"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de mise à jour."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Télécharger depuis GitHub<span style="font-size : 10px;color : gray;text-shadow : none !important ;">Fermer le lanceur et exécuter le dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérifier les mises à jour.."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : impossible de charger l'index de distribution"
fatalErrorMessage = "Une connexion n'a pas pu être établie avec nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'était disponible pour le chargement. <br><br>L'index de distribution est un fichier essentiel qui fournit les dernières informations sur les serveurs. Le lanceur ne peut pas démarrer sans lui. Assurez-vous que vous êtes connecté à l'internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Impossible d'actualiser la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{compte}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{compte}</strong>."
loginButton = "Connexion"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur lors de la connexion:<br>Le profil n'est pas configuré"
noProfileDesc = "Votre compte microsoft n'a pas de profil Minecraft. Assurez-vous d'avoir acheté le jeu."
noXboxAccountTitle = "Erreur lors de la connexion:<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'est pas associé à un compte Xbox."
xblBannedTitle = "Erreur lors de la connexion:<br>Xbox Live n'est pas disponible"
xblBannedDesc = "Votre compte Microsoft provient d'un pays où Xbox Live n'est pas disponible ou est interdit."
under18Title = "Erreur lors de la connexion:<br>Approbation parentale requise"
under18Desc = "Les comptes des utilisateurs de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. Vous pouvez acheter une copie sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."
